# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nyct-subway.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nyct_gtfs.compiled_gtfs.gtfs_realtime_pb2 as gtfs__realtime__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11nyct-subway.proto\x1a\x13gtfs-realtime.proto\"b\n\x15TripReplacementPeriod\x12\x10\n\x08route_id\x18\x01 \x01(\t\x12\x37\n\x12replacement_period\x18\x02 \x01(\x0b\x32\x1b.transit_realtime.TimeRange\"f\n\x0eNyctFeedHeader\x12\x1b\n\x13nyct_subway_version\x18\x01 \x02(\t\x12\x37\n\x17trip_replacement_period\x18\x02 \x03(\x0b\x32\x16.TripReplacementPeriod\"\xa4\x01\n\x12NyctTripDescriptor\x12\x10\n\x08train_id\x18\x01 \x01(\t\x12\x13\n\x0bis_assigned\x18\x02 \x01(\x08\x12\x30\n\tdirection\x18\x03 \x01(\x0e\x32\x1d.NyctTripDescriptor.Direction\"5\n\tDirection\x12\t\n\x05NORTH\x10\x01\x12\x08\n\x04\x45\x41ST\x10\x02\x12\t\n\x05SOUTH\x10\x03\x12\x08\n\x04WEST\x10\x04\"C\n\x12NyctStopTimeUpdate\x12\x17\n\x0fscheduled_track\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63tual_track\x18\x02 \x01(\t:H\n\x10nyct_feed_header\x12\x1c.transit_realtime.FeedHeader\x18\xe9\x07 \x01(\x0b\x32\x0f.NyctFeedHeader:T\n\x14nyct_trip_descriptor\x12 .transit_realtime.TripDescriptor\x18\xe9\x07 \x01(\x0b\x32\x13.NyctTripDescriptor:`\n\x15nyct_stop_time_update\x12+.transit_realtime.TripUpdate.StopTimeUpdate\x18\xe9\x07 \x01(\x0b\x32\x13.NyctStopTimeUpdateB\x1d\n\x1b\x63om.google.transit.realtime')


NYCT_FEED_HEADER_FIELD_NUMBER = 1001
nyct_feed_header = DESCRIPTOR.extensions_by_name['nyct_feed_header']
NYCT_TRIP_DESCRIPTOR_FIELD_NUMBER = 1001
nyct_trip_descriptor = DESCRIPTOR.extensions_by_name['nyct_trip_descriptor']
NYCT_STOP_TIME_UPDATE_FIELD_NUMBER = 1001
nyct_stop_time_update = DESCRIPTOR.extensions_by_name['nyct_stop_time_update']

_TRIPREPLACEMENTPERIOD = DESCRIPTOR.message_types_by_name['TripReplacementPeriod']
_NYCTFEEDHEADER = DESCRIPTOR.message_types_by_name['NyctFeedHeader']
_NYCTTRIPDESCRIPTOR = DESCRIPTOR.message_types_by_name['NyctTripDescriptor']
_NYCTSTOPTIMEUPDATE = DESCRIPTOR.message_types_by_name['NyctStopTimeUpdate']
_NYCTTRIPDESCRIPTOR_DIRECTION = _NYCTTRIPDESCRIPTOR.enum_types_by_name['Direction']
TripReplacementPeriod = _reflection.GeneratedProtocolMessageType('TripReplacementPeriod', (_message.Message,), {
  'DESCRIPTOR' : _TRIPREPLACEMENTPERIOD,
  '__module__' : 'nyct_subway_pb2'
  # @@protoc_insertion_point(class_scope:TripReplacementPeriod)
  })
_sym_db.RegisterMessage(TripReplacementPeriod)

NyctFeedHeader = _reflection.GeneratedProtocolMessageType('NyctFeedHeader', (_message.Message,), {
  'DESCRIPTOR' : _NYCTFEEDHEADER,
  '__module__' : 'nyct_subway_pb2'
  # @@protoc_insertion_point(class_scope:NyctFeedHeader)
  })
_sym_db.RegisterMessage(NyctFeedHeader)

NyctTripDescriptor = _reflection.GeneratedProtocolMessageType('NyctTripDescriptor', (_message.Message,), {
  'DESCRIPTOR' : _NYCTTRIPDESCRIPTOR,
  '__module__' : 'nyct_subway_pb2'
  # @@protoc_insertion_point(class_scope:NyctTripDescriptor)
  })
_sym_db.RegisterMessage(NyctTripDescriptor)

NyctStopTimeUpdate = _reflection.GeneratedProtocolMessageType('NyctStopTimeUpdate', (_message.Message,), {
  'DESCRIPTOR' : _NYCTSTOPTIMEUPDATE,
  '__module__' : 'nyct_subway_pb2'
  # @@protoc_insertion_point(class_scope:NyctStopTimeUpdate)
  })
_sym_db.RegisterMessage(NyctStopTimeUpdate)

if _descriptor._USE_C_DESCRIPTORS == False:
  gtfs__realtime__pb2.FeedHeader.RegisterExtension(nyct_feed_header)
  gtfs__realtime__pb2.TripDescriptor.RegisterExtension(nyct_trip_descriptor)
  gtfs__realtime__pb2.TripUpdate.StopTimeUpdate.RegisterExtension(nyct_stop_time_update)

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033com.google.transit.realtime'
  _TRIPREPLACEMENTPERIOD._serialized_start=42
  _TRIPREPLACEMENTPERIOD._serialized_end=140
  _NYCTFEEDHEADER._serialized_start=142
  _NYCTFEEDHEADER._serialized_end=244
  _NYCTTRIPDESCRIPTOR._serialized_start=247
  _NYCTTRIPDESCRIPTOR._serialized_end=411
  _NYCTTRIPDESCRIPTOR_DIRECTION._serialized_start=358
  _NYCTTRIPDESCRIPTOR_DIRECTION._serialized_end=411
  _NYCTSTOPTIMEUPDATE._serialized_start=413
  _NYCTSTOPTIMEUPDATE._serialized_end=480
# @@protoc_insertion_point(module_scope)
